In [1]:
import pandas as pd

In [2]:
customer=pd.read_excel(r"C:\Users\VISHNU\Downloads\textile_customers.xlsx")
products=pd.read_excel(r"C:\Users\VISHNU\Downloads\textile_products.xlsx")
branches=pd.read_excel(r"C:\Users\VISHNU\Downloads\textile_branches.xlsx")
sales=pd.read_excel(r"C:\Users\VISHNU\Downloads\textile_sales.xlsx")
shopping=pd.read_excel(r"C:\Users\VISHNU\Downloads\shopping_trends.xlsx")

In [3]:
customer.head()

,Customer_ID,Customer_Name,Gender,Age,Home_Branch_ID,Loyalty_Member,Loyalty_Tier,Registration_Date
0,C00001,Joseph Nair,Male,29,B08,Yes,Silver,2024-08-30
1,C00002,Sheela Joseph,Male,52,B07,Yes,Silver,2023-03-17
2,C00003,Praveen Thomas,Female,40,B09,No,NaN,2023-08-03
3,C00004,Vinod Namboothiri,Male,34,B09,Yes,Silver,2023-12-26
4,C00005,Sajan Krishnan,Male,42,B03,No,NaN,2023-01-13

In [4]:
products.head()

,Product_ID,Product_Name,Category,Fabric,MRP_INR,Cost_Price_INR
0,P001,Kanchipuram Silk Saree,Sarees,Silk,8500,6085
1,P002,Kasavu Set Saree,Sarees,Cotton,2800,1902
2,P003,Chiffon Saree,Sarees,Chiffon,1800,1231
3,P004,Cotton Handloom Saree,Sarees,Cotton,1400,800
4,P005,Georgette Party Saree,Sarees,Georgette,2400,1504

In [5]:
sales.head()

,Transaction_ID,Date,Branch_ID,Product_ID,Customer_ID,Quantity,Unit_Price_INR,Discount_Pct,Net_Amount_INR,Payment_Mode,Sales_Channel,Salesperson_ID,Return_Flag
0,T000001,2024-01-01,B03,P025,C00271,2,1800,0,3600,Card,In-Store,B03-S05,No
1,T000002,2024-01-01,B02,P006,C00619,1,6500,5,6175,Cash,In-Store,B02-S06,No
2,T000003,2024-01-01,B02,P036,C01467,1,400,5,380,Cash,In-Store,B02-S08,No
3,T000004,2024-01-01,B03,P027,C00799,4,180,0,720,Cash,In-Store,B03-S07,No
4,T000005,2024-01-01,B03,P024,C00842,1,900,10,810,Cash,In-Store,B03-S06,No

In [6]:
shopping.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
branches.head()

,Branch_ID,Branch_Name,District,Area_Type,Floor_Area_SqFt,Staff_Count,Opening_Date,Monthly_Rent_INR
0,B01,Kochi Central,Ernakulam,Urban,4500,28,2016-03-15,220000
1,B02,Thiruvananthapuram MG Road,Thiruvananthapuram,Urban,5200,32,2014-08-10,410000
2,B03,Kozhikode Mittai Theruvu,Kozhikode,Urban,4000,25,2015-11-01,296000
3,B04,Thrissur Round,Thrissur,Urban,4800,30,2013-04-14,307000
4,B05,Kottayam Town,Kottayam,Semi-Urban,3000,18,2018-09-05,192000

In [12]:
print(branches.isnull().sum())
print(customer.isnull().sum())
print(sales.isnull().sum())
print(products.isnull().sum())
print(shopping.isnull().sum())

Branch_ID           0
Branch_Name         0
District            0
Area_Type           0
Floor_Area_SqFt     0
Staff_Count         0
Opening_Date        0
Monthly_Rent_INR    0
dtype: int64
Customer_ID            0
Customer_Name          0
Gender                 0
Age                    0
Home_Branch_ID         0
Loyalty_Member         0
Loyalty_Tier         785
Registration_Date      0
dtype: int64
Transaction_ID    0
Date              0
Branch_ID         0
Product_ID        0
Customer_ID       0
Quantity          0
Unit_Price_INR    0
Discount_Pct      0
Net_Amount_INR    0
Payment_Mode      0
Sales_Channel     0
Salesperson_ID    0
Return_Flag       0
dtype: int64
Product_ID        0
Product_Name      0
Category          0
Fabric            0
MRP_INR           0
Cost_Price_INR    0
dtype: int64
Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)       0
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Payment Method              0
Shipping Type               0
Discount Applied            0
Promo Code Used             0
Previous Purchases          0
Preferred Payment Method    0
Frequency of Purchases      0
dtype: int64

In [13]:
customer["Loyalty_Tier"] = customer["Loyalty_Tier"].fillna("Unknown")

In [15]:
customer.isnull().sum()

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
Home_Branch_ID       0
Loyalty_Member       0
Loyalty_Tier         0
Registration_Date    0
dtype: int64

In [17]:
print("Duplicate Customer:", customer.duplicated().sum())
print("Duplicate Sales:", sales.duplicated().sum())
print("Duplicate branches:", branches.duplicated().sum())
print("Duplicate Shopping:", shopping.duplicated().sum())
print("Duplicate products:", products.duplicated().sum())

Duplicate Customer: 0
Duplicate Sales: 0
Duplicate branches: 0
Duplicate Shopping: 0
Duplicate products: 0

In [18]:
pip install pandas openpyxl matplotlib seaborn sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\vishnu\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\vishnu\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\vishnu\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\vishnu\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: sqlalchemy in c:\users\vishnu\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\vishnu\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\vishnu\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: greenlet>=1 in c:\users\vishnu\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vishnu\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\vishnu\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:mysql40@localhost/textile")
print("connected to MYSQL")

connected to MYSQL

In [ ]:
customer.to_sql("customer",con=engine,if_exists="replace",index=False)
products.to_sql("products", engine, if_exists="replace", index=False)
shopping.to_sql("shopping", engine, if_exists="replace", index=False)
sales.to_sql("sales", engine, if_exists="replace", index=False)
branches.to_sql("branches", engine, if_exists="replace", index=False)